
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - dist
      - cypress
  workflow_dispatch:

permissions:
  contents: write

env:
  TZ: 'Asia/Shanghai'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm i

      - run: pnpm run dist && ls -l dist

      - name: Deploy to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
          tag_name: zipped_dist
